
name: "Build ffmpeg"

on: [push]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        name: [raspbian-armv6l, debian-x86_64, debian-armv7l, alpine-x86_64, alpine-armv6l]
        include:
          - name: raspbian-armv6l
            os: ubuntu-latest
            BASE_IMAGE: balenalib/raspberry-pi-debian:stretch
            DOCKERFILE: Dockerfile.debian
            TARGET_OS: raspbian
          - name: debian-x86_64
            os: ubuntu-latest
            BASE_IMAGE: library/debian:stretch
            DOCKERFILE: Dockerfile.debian
            TARGET_OS: debian
          - name: debian-armv7l
            os: ubuntu-latest
            BASE_IMAGE: arm32v7/debian:stretch
            DOCKERFILE: Dockerfile.debian
            TARGET_OS: debian
          - name: alpine-x86_64
            os: ubuntu-latest
            BASE_IMAGE: library/alpine:3.11.3
            DOCKERFILE: Dockerfile.alpine
            TARGET_OS: alpine
          - name: alpine-armv6l
            os: ubuntu-latest
            BASE_IMAGE: arm32v6/alpine:3.11.3
            DOCKERFILE: Dockerfile.alpine
            TARGET_OS: alpine

    steps:
    - uses: actions/checkout@v2
    - name: Cache Workspace
      id: cache
      uses: actions/cache@v1
      with:
        path: build
        key: ${{ matrix.name }}-cache
    - name: Setup Dependencies
      run: |
        sudo apt-get update
        sudo apt-get --yes --no-install-recommends install binfmt-support qemu-user-static
        docker run --rm --privileged multiarch/qemu-user-static:register --reset
    - name: Build Docker Image 
      run: |
        docker build --build-arg BASE_IMAGE=${{ matrix.BASE_IMAGE }} -f ${{ matrix.DOCKERFILE }} -t ffmpeg-builder .
    - name: Build static ffmpeg binary
      run: |
        mkdir -p build
        docker run -v $(pwd)/build:/build -e TARGET_OS=${{ matrix.TARGET_OS }} ffmpeg-builder
    - name: Fix permissions
      run: |
        sudo chown -R $USER:$USER build
    - name: Upload Assets
      uses: actions/upload-artifact@v1
      with:
        name: ffmpeg-${{ matrix.name }}
        path: build/workspace/bin/ffmpeg